# FastMCP Cloud Configuration
# Keep only supported sections for deployment

[project]
name = "catabus-mcp"
version = "0.1.0"
description = "MCP server for CATA bus system live and static schedule data"

[server]
module = "catabus_mcp.server"
server_object = "server"

[environment]
TZ = "America/New_York"